### PR TITLE
Don't treat `SyncRecord` as thread-safe

### LINKED ISSUE #19: unsoundness (race condition)
You are implementing `Record` for `SyncRecord<'a>`, which contains a `fmt::Arguments<'a>`. This allows triggering a race condition (https://github.com/rust-lang/rust/issues/45197), that will be fixed in Rust in the future (https://github.com/rust-lang/rust/pull/45198).

I checked what happens when only implementing `Record` for `SyncRecord<'static>`, but that makes `woodpecker` unusable:

```
error[E0597]: borrowed value does not live long enough
   --> src/logger.rs:578:22
    |
578 |                 log!(">>{}<<", "unconditional");
    |                 -----^^^^^^^^-------------------
    |                 |    |
    |                 |    does not live long enough
    |                 in this macro invocation
    |
   ::: src/macros/helpers.rs
    |
33  |         })
    |         - temporary value only lives until here
    |
    = note: borrowed value must be valid for the static lifetime...

error[E0597]: borrowed value does not live long enough
   --> src/logger.rs:733:35
    |
733 |                             info!("{}", idx);
    |                             ------^^^^-------
    |                             |     |
    |                             |     does not live long enough
    |                             in this macro invocation
    |
   ::: src/macros/helpers.rs
    |
33  |         })
    |         - temporary value only lives until here
    |
    = note: borrowed value must be valid for the static lifetime...

error[E0597]: `idx` does not live long enough
   --> src/logger.rs:733:41
    |
733 |                             info!("{}", idx);
    |                                         ^^^ does not live long enough
    |
   ::: src/macros/helpers.rs
    |
33  |         })
    |         - borrowed value only lives until here
    |
    = note: borrowed value must be valid for the static lifetime...

error[E0597]: borrowed value does not live long enough
   --> src/logger.rs:735:32
    |
735 |                         debug!("{}", idx);
    |                         -------^^^^-------
    |                         |      |
    |                         |      does not live long enough
    |                         in this macro invocation
    |
   ::: src/macros/helpers.rs
    |
33  |         })
    |         - temporary value only lives until here
    |
    = note: borrowed value must be valid for the static lifetime...

error[E0597]: `idx` does not live long enough
   --> src/logger.rs:735:38
    |
735 |                         debug!("{}", idx);
    |                                      ^^^ does not live long enough
    |
   ::: src/macros/helpers.rs
    |
33  |         })
    |         - borrowed value only lives until here
    |
    = note: borrowed value must be valid for the static lifetime...

error[E0597]: borrowed value does not live long enough
   --> src/logger.rs:733:35
    |
733 |                             info!("{}", idx);
    |                             ------^^^^-------
    |                             |     |
    |                             |     does not live long enough
    |                             in this macro invocation
    |
   ::: src/macros/logging.rs
    |
86  |                     root.log(&RECORD, format_args!($($arg)*));
    |                                                              - temporary value only lives until here
    |
    = note: borrowed value must be valid for the static lifetime...
    = note: consider using a `let` binding to increase its lifetime

error[E0597]: `idx` does not live long enough
   --> src/logger.rs:733:41
    |
733 |                             info!("{}", idx);
    |                                         ^^^ does not live long enough
    |
   ::: src/macros/logging.rs
    |
88  |             });
    |             - borrowed value only lives until here
    |
    = note: borrowed value must be valid for the static lifetime...

error[E0597]: borrowed value does not live long enough
   --> src/logger.rs:735:32
    |
735 |                         debug!("{}", idx);
    |                         -------^^^^-------
    |                         |      |
    |                         |      does not live long enough
    |                         in this macro invocation
    |
   ::: src/macros/logging.rs
    |
86  |                     root.log(&RECORD, format_args!($($arg)*));
    |                                                              - temporary value only lives until here
    |
    = note: borrowed value must be valid for the static lifetime...
    = note: consider using a `let` binding to increase its lifetime

error[E0597]: `idx` does not live long enough
   --> src/logger.rs:735:38
    |
735 |                         debug!("{}", idx);
    |                                      ^^^ does not live long enough
    |
   ::: src/macros/logging.rs
    |
88  |             });
    |             - borrowed value only lives until here
    |
    = note: borrowed value must be valid for the static lifetime...
```

I'm not sure how to proceed here.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #19

### CODE REVIEW

**Comment by niamster** [comment]
Could you please explain this `PhantomData` magic?

**Comment by cuviper** [comment]
It prevents the default implementation of OIBITS -- [opt-in builtin traits](https://github.com/rust-lang/rfcs/blob/master/text/0019-opt-in-builtin-traits.md) like `Send` and `Sync`.  `PhantomData` adds no actual size to your struct, but since the referenced `*mut Fn()` doesn't implement OIBITs, then neither will your struct containing it.

**Comment by niamster** [comment]
However we don't really need this magic if trait `SyncRecord` doesn't require `Sync+Send` isn't it?

**Comment by oli-obk** [comment]
You can still send a `SyncRecord` across threads without this. Once the PR on the Rust side is fixed, you can remove the `PhantomData` again

**Pull request merged**
